version: '3'
services: 
  rasa-bot:
    image: rasa/rasa:2.1.0-full
    ports: 
      - 5005:5005
    volumes: 
      - ..:/app
    networks: 
      - my-project
    command: 
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
  action-server:
    image: rasa/rasa-sdk:2.2.0
    volumes: 
      - ../actions:/app/actions
    networks: 
      - my-project
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: siddybot
    networks: 
      - my-project
  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: siddybot
    networks: 
      - my-project
networks: 
  my-project:
    external: true